name: 'Create a pre-release'
description: 'Create a pre-release'
inputs:
  pre_release_branch:
    description: The branch will be merged to the main branch before creating the release
    default: $ {{ github.ref_name }}
runs:
  using: "composite"
  steps:
    - name: Checkout to the root
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup node environment
      uses: actions/setup-node@v3
      env:
        CI: true
      with:
        node-version: 16.13.2

    - name: Clear cache
      run: npm cache clear --force

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Create a pre-release
      run: node dist/main.js


